name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install .[test]
      - name: Validate linter rules with Ruff
        uses: chartboost/ruff-action@v1
      - name: Validate formatting with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
